### ISSUE TITLE
溯 Resux keeps stopping

### ISSUE THREAD

**Issue by Nekitori17** [piae-mentes-project/Resux-OpenSource#1]
Logcat.txt: 
```
07-27 12:04:56.030 D/CompatibilityChangeReporter( 1719): Compat change id reported: 161252188; UID 10430; state: DISABLED
07-27 12:04:56.030 I/ActivityTaskManager( 1719): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.tenMinStudio.Resux/.AndroidPlatform.MainActivity bnds=[436,470][644,836]} from uid 10340

07-27 12:04:56.054 D/CoreBackPreview( 1719): Window{75d70aa u0 Splash Screen com.tenMinStudio.Resux}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@dd3a811, mPriority=0}

07-27 12:04:56.065 I/ActivityManager( 1719): Start proc 5572:com.tenMinStudio.Resux/u0a430 for next-top-activity {com.tenMinStudio.Resux/com.tenMinStudio.Resux.AndroidPlatform.MainActivity}

07-27 12:04:56.107 E/MinStudio.Resux( 5572): Not starting debugger since process cannot load the jdwp agent.

07-27 12:04:56.146 W/MinStudio.Resux( 5572): Core platform API violation: Ljava/lang/reflect/Field;->accessFlags:I from Landroid/os/Build; using reflection

07-27 12:04:56.178 V/GraphicsEnvironment( 5572): ANGLE Developer option for 'com.tenMinStudio.Resux' set to: 'default'

07-27 12:04:56.179 V/GraphicsEnvironment( 5572): ANGLE GameManagerService for com.tenMinStudio.Resux: false
07-27 12:04:56.179 V/GraphicsEnvironment( 5572): Neither updatable production driver nor prerelease driver is supported.

07-27 12:04:56.192 I/Resux   ( 5572): Resux start!

07-27 12:04:56.233 I/Resux   ( 5572): Resux inited.

07-27 12:04:56.246 D/CoreBackPreview( 1719): Window{9ec1fac u0 com.tenMinStudio.Resux/com.tenMinStudio.Resux.AndroidPlatform.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@39a8c0a, mPriority=0}

07-27 12:04:56.319 D/CompatibilityChangeReporter( 5572): Compat change id reported: 78294732; UID 10430; state: DISABLED
07-27 12:04:56.319 D/AndroidRuntime( 5572): Shutting down VM
07-27 12:04:56.320 E/AndroidRuntime( 5572): FATAL EXCEPTION: main
07-27 12:04:56.320 E/AndroidRuntime( 5572): Process: com.tenMinStudio.Resux, PID: 5572
07-27 12:04:56.320 E/AndroidRuntime( 5572): java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at com.tenMinStudio.Resux.AndroidPlatform.MainActivity.onRequestPermissionsResult(Unknown Source:2)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8834)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.Activity.dispatchActivityResult(Activity.java:8692)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5338)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5384)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.os.Looper.loopOnce(Looper.java:201)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.os.Looper.loop(Looper.java:288)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at android.app.ActivityThread.main(ActivityThread.java:7934)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at java.lang.reflect.Method.invoke(Native Method)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
07-27 12:04:56.320 E/AndroidRuntime( 5572): Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
07-27 12:04:56.320 E/AndroidRuntime( 5572): 	... 17 more
07-27 12:04:56.321 W/libprocessgroup( 1719): Failed to open /dev/blkio//cgroup.procs: No such file or directory

07-27 12:04:56.331 W/ActivityTaskManager( 1719):   Force finishing activity com.tenMinStudio.Resux/.AndroidPlatform.MainActivity
07-27 12:04:56.333 D/ActivityTrigger( 1719): ActivityTrigger activityPauseTrigger 

07-27 12:04:56.355 I/WindowManager( 1719): WIN DEATH: Window{9ec1fac u0 com.tenMinStudio.Resux/com.tenMinStudio.Resux.AndroidPlatform.MainActivity}
07-27 12:04:56.355 I/ActivityManager( 1719): Process com.tenMinStudio.Resux (pid 5572) has died: fg  TOP 

07-27 12:04:56.356 W/InputManager-JNI( 1719): Input channel object '9ec1fac com.tenMinStudio.Resux/com.tenMinStudio.Resux.AndroidPlatform.MainActivity (client)' was disposed without first being removed with the input manager!
07-27 12:04:56.356 I/libprocessgroup( 1719): Successfully killed process cgroup uid 10430 pid 5572 in 0ms

07-27 12:04:56.374 W/WindowManager( 1719): Failed to deliver inset state change to w=Window{9ec1fac u0 com.tenMinStudio.Resux/com.tenMinStudio.Resux.AndroidPlatform.MainActivity EXITING}
07-27 12:04:56.374 W/WindowManager( 1719): android.os.DeadObjectException
07-27 12:04:56.374 W/WindowManager( 1719): 	at android.os.BinderProxy.transactNative(Native Method)
07-27 12:04:56.374 W/WindowManager( 1719): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
07-27 12:04:56.374 W/WindowManager( 1719): 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4017)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4(InsetsStateController.java:351)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.InsetsStateController.$r8$lambda$An2IoiA3BeA5IWc6QwBOjKArM80(Unknown Source:0)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda3.run(Unknown Source:2)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:840)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:785)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.WindowSurfacePlacer.continueLayout(WindowSurfacePlacer.java:97)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.ActivityTaskManagerService.continueWindowLayout(ActivityTaskManagerService.java:4551)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.wm.ActivityTaskManagerService$LocalService.handleAppDied(ActivityTaskManagerService.java:6158)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3300)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3405)
07-27 12:04:56.374 W/WindowManager( 1719): 	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1491)
07-27 12:04:56.374 W/WindowManager( 1719): 	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:317)
07-27 12:04:56.374 W/WindowManager( 1719): 	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:704)
07-27 12:04:56.375 W/OpenGLRenderer( 3334): dequeueBuffer failed, error = -110; switching to fallback

07-27 12:04:56.615 W/WindowManager( 1719): Exception thrown during dispatchAppVisibility Window{9ec1fac u0 com.tenMinStudio.Resux/com.tenMinStudio.Resux.AndroidPlatform.MainActivity EXITING}
07-27 12:04:56.615 W/WindowManager( 1719): android.os.DeadObjectException
07-27 12:04:56.615 W/WindowManager( 1719): 	at android.os.BinderProxy.transactNative(Native Method)
07-27 12:04:56.615 W/WindowManager( 1719): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
07-27 12:04:56.615 W/WindowManager( 1719): 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3484)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1231)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:392)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6807)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7638)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.WindowContainer.doAnimationFinished(WindowContainer.java:3348)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.WindowContainer.onAnimationFinished(WindowContainer.java:3360)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.WindowContainer$$ExternalSyntheticLambda4.onAnimationFinished(Unknown Source:2)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0(SurfaceAnimator.java:133)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.SurfaceAnimator.$r8$lambda$lRxTVOJy8fX752UbrFno9INW9hE(Unknown Source:0)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda1.run(Unknown Source:8)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1(SurfaceAnimator.java:143)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.SurfaceAnimator.$r8$lambda$4PiCdaEsT4mA6LQVhqpeM5EoU9c(Unknown Source:0)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.SurfaceAnimator$$ExternalSyntheticLambda0.onAnimationFinished(Unknown Source:4)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.RemoteAnimationController.onAnimationFinished(RemoteAnimationController.java:307)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.RemoteAnimationController.-$$Nest$monAnimationFinished(Unknown Source:0)
07-27 12:04:56.615 W/WindowManager( 1719): 	at com.android.server.wm.RemoteAnimationController$FinishedCallback.onAnimationFinished(RemoteAnimationController.java:418)
07-27 12:04:56.615 W/WindowManager( 1719): 	at android.view.IRemoteAnimationFinishedCallback$Stub.onTransact(IRemoteAnimationFinishedCallback.java:89)
07-27 12:04:56.615 W/WindowManager( 1719): 	at android.os.Binder.execTransactInternal(Binder.java:1285)
07-27 12:04:56.615 W/WindowManager( 1719): 	at android.os.Binder.execTransact(Binder.java:1244)
07-27 12:04:56.615 I/Process ( 1719): Sending signal. PID: 5572 SIG: 9

07-27 12:04:56.619 W/InputManager-JNI( 1719): Input channel object '75d70aa Splash Screen com.tenMinStudio.Resux (client)' was disposed without first being removed with the input manager!

07-27 12:04:56.832 W/ActivityTaskManager( 1719): Activity top resumed state loss timeout for ActivityRecord{cb10b4c u0 com.tenMinStudio.Resux/.AndroidPlatform.MainActivity} t-1 f}}

``` 
![Screenshot_20240727-113232_NusantaraLauncher](https://github.com/user-attachments/assets/b2d35f90-f21c-4075-ab0f-821ac58c7fbe)

**Comment by SlipperSoar** [comment]
[From machine translation]
这个出问题的安卓侧方法并没有在游戏内被使用，现在已被移除，当前已可以构建出正常游玩的apk。
The problematic Android side method has not been used in the game and has now been removed. It is now possible to build an APK for normal gameplay.
另外：该方法不属于alpha测试内容，是为了能够在启动时检测蓝牙耳机以自动适配延迟而追加的内容。
Additionally, this method is not part of the alpha testing scope and is an additional feature added to enable automatic adaptation delay detection of Bluetooth earphones during startup.

@Nekitori17

**Comment by SlipperSoar** [comment]
Android Plugin Project Path：Client/PlatformInterfaces/Android

You can also attempt to develop your own Bluetooth earphone detection method to enhance the gaming experience.

Thank you for discovering this issue.

**Comment by Nekitori17** [comment]
Ok. I will do it myself . Even though I don't have a computer XD

**Comment by SlipperSoar** [comment]
Ok 
Then I will upload the new apk to release tonight（UTC+8）

**Comment by SlipperSoar** [comment]
Now I have uploaded the new apk in release v1.0.1

I'm sorry for being so late, now there is 02:27 am. XD

**Comment by Nekitori17** [comment]
# Hold up. It's still have bug lmao.
```
Login exception: System.NullReferenceException: Object reference not set to an instance of an object.
    at Resux.UI.Manager.EntrySceneController.InitDataBySavedArchive () (0x00000] in
            <00000000000000000000000000000000>:()
    at Resux.UI.Manager.EntrySceneController.Login()
```
![Screenshot_20240806-100644](https://github.com/user-attachments/assets/29366859-b3cc-4864-8280-d5b32ba2dee9)

**Comment by Nekitori17** [comment]
It happens on the second login

**Comment by SlipperSoar** [comment]
Oh sorry, this looks like another bug.
I will fix it tonight as much as possible.

In fact, I guess this login exception is caused by unclear code about server, even though I have deleted the code about taptap sdk.

Next time I will test a complete process then upload new apk file.

**Comment by SlipperSoar** [comment]
I'm so sorry that I do nothing about this yesterday, because I really didn't have time yesterday. 
Now I have fixed the problem and can play normally, including normal local saves (please note that the saves will disappear after uninstallation)

The new apk file has been uploaded at Release/v1.0.2，you can download and try it again.

**Comment by Nekitori17** [comment]
## Resolved
Thanks for your efforts

**Comment by Nekitori17** [comment]
## Resolved
Thanks for your efforts
